version: '3.8'

services:
  temporal:
    container_name: temporal
    environment:
      - DB=sqlite
      - ENABLE_ES=false
      - LOG_LEVEL=warn,info
    image: temporalio/auto-setup:1.24.1
    networks:
      - temporal-network
    ports:
      - 7233:7233
    volumes:
      - temporal_data:/tmp/temporal

  temporal-ui:
    container_name: temporal-ui
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
    image: temporalio/ui:2.29.1
    networks:
      - temporal-network
    ports:
      - 8080:8080

networks:
  temporal-network:
    driver: bridge
    name: temporal-network

volumes:
  temporal_data:
