app = "pip-ai-unstructured-simple"
primary_region = "iad"

[experimental]
  auto_rollback = true

[env]
  UNSTRUCTURED_HOST = "0.0.0.0"
  UNSTRUCTURED_PORT = "8000"
  UNSTRUCTURED_WORKERS = "4"
  PYTHONUNBUFFERED = "1"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 2
  max_machines_running = 4

  [[http_service.checks]]
    grace_period = "30s"
    interval = "15s"
    method = "GET"
    path = "/healthcheck"
    timeout = "5s"

[build]
  image = "downloads.unstructured.io/unstructured-io/unstructured:latest"

[vm]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 4096

[deploy]
  strategy = "rolling"

[[restart]]
  policy = "always" 