app = "pip-ai-unstructured-ha"
primary_region = "iad"
console_command = "/bin/bash"

[experimental]
  auto_rollback = true

# HIGH AVAILABILITY CONFIGURATION
[env]
  UNSTRUCTURED_HOST = "0.0.0.0"
  UNSTRUCTURED_PORT = "8000"
  UNSTRUCTURED_WORKERS = "4"
  PYTHONUNBUFFERED = "1"
  # Production optimizations
  UNSTRUCTURED_CACHE_ENABLED = "true"
  UNSTRUCTURED_MAX_WORKERS = "8"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 2  # Always keep 2+ instances running
  max_machines_running = 6  # Scale up to 6 instances under load

  # COMPREHENSIVE HEALTH CHECKS
  [[http_service.checks]]
    grace_period = "30s"
    interval = "10s"
    method = "GET"
    path = "/healthcheck"
    timeout = "5s"
    headers = { }

  # PERFORMANCE HEALTH CHECK
  [[http_service.checks]]
    grace_period = "45s"
    interval = "30s"
    method = "GET"
    path = "/performance-stats"
    timeout = "10s"

[build]
  image = "downloads.unstructured.io/unstructured-io/unstructured:latest"

# HIGH-PERFORMANCE VM CONFIGURATION
[vm]
  cpu_kind = "shared"
  cpus = 4  # Increased CPU for better performance
  memory_mb = 8192  # Increased memory for better performance

# DEPLOYMENT STRATEGY
[deploy]
  strategy = "rolling"
  max_unavailable = 0  # Zero-downtime deployments

# ENHANCED MONITORING
[metrics]
  port = 8000
  path = "/performance-stats"

# RESTART POLICY FOR HIGH AVAILABILITY
[[restart]]
  policy = "always" 