app = "pip-ai-unstructured-simple"
primary_region = "iad"

[experimental]
  auto_rollback = true

[env]
  UNSTRUCTURED_HOST = "0.0.0.0"
  UNSTRUCTURED_PORT = "8000"
  UNSTRUCTURED_WORKERS = "8"
  UNSTRUCTURED_MAX_THREADS = "32"
  PYTHONUNBUFFERED = "1"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 2

  [[http_service.checks]]
    grace_period = "60s"
    interval = "30s"
    method = "GET"
    path = "/healthcheck"
    timeout = "10s"

[build]
  image = "downloads.unstructured.io/unstructured-io/unstructured:latest"

[vm]
  gpu_kind = "l40s"
  cpus = 8
  memory_mb = 32768

[deploy]
  strategy = "rolling"
  max_unavailable = 0

[[restart]]
  policy = "always" 