packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - '@temporalio/core-bridge'
  - aws-sdk
  - esbuild
  - prisma
  - protobufjs
  - sharp
  - unrs-resolver
