import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// Force entire app to be dynamic - this is critical for Next.js 15
export const dynamic = 'force-dynamic';
export const dynamicParams = true;
export const revalidate = false;

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
