import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// CRITICAL: Force all pages to be dynamic to avoid Html import error during static generation
export const dynamic = 'force-dynamic';
export const dynamicParams = true;
export const revalidate = 0;

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
