# PIP AI Temporal Worker - Fly.io Configuration

app = 'pip-ai-temporal-workers'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  NODE_ENV = 'production'
  LOG_LEVEL = 'info'

# No services block needed for background worker
# This is a background service that doesn't serve HTTP traffic

[[vm]]
  memory = '8gb'
  cpu_kind = 'performance'
  cpus = 2